### ISSUE TITLE
Extension needs queries updated due to Actor migration

### ISSUE THREAD

**Issue by clintljohnson** [nicjansma/mediawiki-Extension-SpecialUserScore#3]
MediaWiki 1.31 introduces the concept of actors which breaks the query in this extension that produces the output.  The issue appears to require a fairly simple modification but I haven't taken this on because I'm not quite sure if direct DB access should be avoided in favor of getQueryInfo() methods mentioned in [Actor migration](https://www.mediawiki.org/wiki/Actor_migration) 

SELECT COUNT(rev_id) as value,COUNT(DISTINCT rev_page) as page_value,user_name as title,2 as namespace FROM `user`,`revision`,`page` WHERE (user_id = rev_user) AND (page_id = rev_page) AND (page_namespace = 0) GROUP BY user_name ORDER BY value DESC LIMIT 51

MySQL said: 
#1054 - Unknown column 'rev_user' in 'where clause'

**Comment by nicjansma** [comment]
via https://github.com/nicjansma/mediawiki-Extension-SpecialUserScore/pull/4
